### ISSUE TITLE
Hover Text über Menü und 'Stecknadel' Ikonen zufügen?

### ISSUE THREAD

**Issue by reinisindans** [LorenMucha/IOER-Monitor#53]
Es wäre möglich einen kurzen erklärungstext als *'hover text*' auch bei die 'Menü' Leiste und 'Stecknadel' Ikonen bei Parameterauswahlleiste zufügen. Genau wie es bei 'Zoom' 'Ausdehnung' und 'Tabelle Ikonen gemacht ist
![menue](https://user-images.githubusercontent.com/33867336/50909440-1f6f1180-142c-11e9-9995-2d153b038666.png)

**Comment by LorenMucha** [comment]
Guter Punkt -> erledigt
