### ISSUE TITLE
Indikator 'Siedlungsdichte' unter Indikatorkategorien 'Nachhaltigkeit' UND 'Bevölkerungsbezug aufgelistet

### ISSUE THREAD

**Issue by reinisindans** [LorenMucha/IOER-Monitor#58]
Indikator 'Siedlungsdichte' unter Indikatorkategorien 'Nachhaltigkeit' UND 'Bevölkerungsbezug aufgelistet. Aber nicht unter 'Siedlung'...

**Comment by LorenMucha** [comment]
-> Beschluss Kerngruppe, aber interessanter Punkt
